/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as EducationRouteImport } from './routes/education'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsSlugRouteImport } from './routes/skills.$slug'

const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const EducationRoute = EducationRouteImport.update({
  id: '/education',
  path: '/education',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsSlugRoute = SkillsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SkillsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/education': typeof EducationRoute
  '/experience': typeof ExperienceRoute
  '/projects': typeof ProjectsRoute
  '/publications': typeof PublicationsRoute
  '/skills': typeof SkillsRouteWithChildren
  '/skills/$slug': typeof SkillsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/education'
    | '/experience'
    | '/projects'
    | '/publications'
    | '/skills'
    | '/skills/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/education'
    | '/experience'
    | '/projects'
    | '/publications'
    | '/skills'
    | '/skills/$slug'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/education'
    | '/experience'
    | '/projects'
    | '/publications'
    | '/skills'
    | '/skills/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  EducationRoute: typeof EducationRoute
  ExperienceRoute: typeof ExperienceRoute
  ProjectsRoute: typeof ProjectsRoute
  PublicationsRoute: typeof PublicationsRoute
  SkillsRoute: typeof SkillsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/education': {
      id: '/education'
      path: '/education'
      fullPath: '/education'
      preLoaderRoute: typeof EducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$slug': {
      id: '/skills/$slug'
      path: '/$slug'
      fullPath: '/skills/$slug'
      preLoaderRoute: typeof SkillsSlugRouteImport
      parentRoute: typeof SkillsRoute
    }
  }
}

interface SkillsRouteChildren {
  SkillsSlugRoute: typeof SkillsSlugRoute
}

const SkillsRouteChildren: SkillsRouteChildren = {
  SkillsSlugRoute: SkillsSlugRoute,
}

const SkillsRouteWithChildren =
  SkillsRoute._addFileChildren(SkillsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  EducationRoute: EducationRoute,
  ExperienceRoute: ExperienceRoute,
  ProjectsRoute: ProjectsRoute,
  PublicationsRoute: PublicationsRoute,
  SkillsRoute: SkillsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
